### ISSUE TITLE
数据库的表结构能否提供一下?

### ISSUE THREAD

**Issue by WittFan** [sunhailin-Leo/BOC_FER_Spider#1]
数据库相关的sql

**Comment by sunhailin-Leo** [comment]
@WittFan 
* SQL: https://github.com/sunhailin-Leo/BOC_FER_Spider/blob/master/BOC_FER_Spider/utils/enum_variable.py#L53

**Comment by sunhailin-Leo** [comment]
@WittFan 我把 SQL 写死在代码里，自动会创建的

**Comment by WittFan** [comment]
谢谢，最好也能趴一趴香港的离岸人民币价格，这个和在岸价格差1%左右。
